# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
# Copyright 2020 The sv2chisel Authors. All rights reserved.

# Config file format: list of projects
- name: LcdPjt #project name, optional
  emissionPath: "chisel_gen/lcd_pjt" #base path of translated files, optional
  basePath: "src/main/resources/project/hdl" #base path of files to be translated, optional
  files: #list of files to be translated into chisel, at least one file is required
    - gowin_osc/gowin_osc.v
    - gowin_pll/gowin_pll.v
    - TOP.v
    - VGAMod.v
    
  translationOptions:
    LegalizeParamDefaults:
      legalizeMethod: moveOrOverride # comment|overrideOption|moveOrComment|moveOrOverride
    RemoveConcats:
      useChiselCat: true
    Chiselizer:
      toCamelCase: false
      ignoreEnumFieldScalastyle: false
      unpackedEmissionStyle: Reg # Reg|Mem
      topLevelChiselGenerators: # list of top in the project 
        - name: TOP # name of top
          withWrapper: true # provide a wrapper for params and with structural ports
          
      # baseBlackboxRessourcePath must contains /resources/ to be valid
      # - sv files are copied there
      # - blackboxes are mixed with HasBlackBoxResource trait and features a addRessource("path")
      baseBlackboxRessourcePath: "" 
  
