package hdl
package gowin_pll

import chisel3._
import chisel3.experimental.Param
//Copyright (C)2014-2019 Gowin Semiconductor Corporation.
//All rights reserved.
//File Title: IP file
//GOWIN Version: v1.9.2Beta
//Part Number: GW1N-LV1QN48C6/I5
//Created Time: Fri Oct 25 15:23:07 2019

class PLL(val pm: Map[String, Param]) extends BlackBox(pm){
    val io = IO(new Bundle{
        val CLKOUT = Output(Clock())
        val LOCK = Output(UInt(1.W))
        val CLKOUTP = Output(Clock())
        val CLKOUTD = Output(Clock())
        val CLKOUTD3 = Output(Clock())
        val RESET = Input(UInt(1.W))
        val RESET_P = Input(UInt(1.W))
        val RESET_I = Input(UInt(1.W))
        val RESET_S = Input(UInt(1.W))
        val CLKIN = Input(Clock())
        val CLKFB = Input(Bool())
        val FBDSEL = Input(UInt(6.W))
        val IDSEL = Input(UInt(6.W))
        val ODSEL = Input(UInt(6.W))
        val PSDA = Input(UInt(4.W))
        val DUTYDA = Input(UInt(4.W))
        val FDLY = Input(UInt(4.W))
    })
}

class Gowin_PLL() extends RawModule {

  val clkout = IO(Output(Clock()))
  val clkoutd = IO(Output(Clock()))
  val clkin = IO(Input(Clock()))

  val pm: Map[String, Param] = Map(
  "FCLKIN" -> "24",
  "DYN_IDIV_SEL" -> "false",
  "IDIV_SEL" -> 2,
  "DYN_FBDIV_SEL" -> "false",
  "FBDIV_SEL" -> 24,
  "DYN_ODIV_SEL" -> "false",
  "ODIV_SEL" -> 4,
  "PSDA_SEL" -> "0000",
  "DYN_DA_EN" -> "true",
  "DUTYDA_SEL" -> "1000",
  "CLKOUT_FT_DIR" -> "1'b1",
  "CLKOUTP_FT_DIR" -> "1'b1",
  "CLKOUT_DLY_STEP" -> 0,
  "CLKOUTP_DLY_STEP" -> 0,
  "CLKFB_SEL" -> "internal",
  "CLKOUT_BYPASS" -> "false",
  "CLKOUTP_BYPASS" -> "false",
  "CLKOUTD_BYPASS" -> "false",
  "DYN_SDIV_SEL" -> 6,
  "CLKOUTD_SRC" -> "CLKOUT",
  "CLKOUTD3_SRC" -> "CLKOUT",
  "DEVICE" -> "GW1N-1")

  val lock_o = Wire(Bool()) 
  val clkoutp_o = Wire(Clock())
  val clkoutd3_o = Wire(Clock())
  val gw_gnd = Wire(Bool()) 
  gw_gnd := false.B
  // NOTE: The following statements are auto generated due to the use of concatenation in port-map of instance pll_inst
  //       This default translation is very verbose, you may hence want to refactor it by:
  //          > (TO DO AUTOMATICALLY?) Remove existing wire declaration used in concat {<w1>, <w2>, ...} and rename those wire as <bundleName>.<w1> wherever used.
  //          > Reuse same autogenerated bundle for in and out of extra (use chiselTypeOf())
  val pll_inst_FBDSEL = Wire(new Bundle { 
    val gw_gnd = Bool()
    val gw_gnd_0 = Bool()
    val gw_gnd_1 = Bool()
    val gw_gnd_2 = Bool()
    val gw_gnd_3 = Bool()
    val gw_gnd_4 = Bool()
  }) 
  pll_inst_FBDSEL.gw_gnd := gw_gnd
  pll_inst_FBDSEL.gw_gnd_0 := gw_gnd
  pll_inst_FBDSEL.gw_gnd_1 := gw_gnd
  pll_inst_FBDSEL.gw_gnd_2 := gw_gnd
  pll_inst_FBDSEL.gw_gnd_3 := gw_gnd
  pll_inst_FBDSEL.gw_gnd_4 := gw_gnd
  val pll_inst_IDSEL = Wire(new Bundle { 
    val gw_gnd = Bool()
    val gw_gnd_0 = Bool()
    val gw_gnd_1 = Bool()
    val gw_gnd_2 = Bool()
    val gw_gnd_3 = Bool()
    val gw_gnd_4 = Bool()
  }) 
  pll_inst_IDSEL.gw_gnd := gw_gnd
  pll_inst_IDSEL.gw_gnd_0 := gw_gnd
  pll_inst_IDSEL.gw_gnd_1 := gw_gnd
  pll_inst_IDSEL.gw_gnd_2 := gw_gnd
  pll_inst_IDSEL.gw_gnd_3 := gw_gnd
  pll_inst_IDSEL.gw_gnd_4 := gw_gnd
  val pll_inst_ODSEL = Wire(new Bundle { 
    val gw_gnd = Bool()
    val gw_gnd_0 = Bool()
    val gw_gnd_1 = Bool()
    val gw_gnd_2 = Bool()
    val gw_gnd_3 = Bool()
    val gw_gnd_4 = Bool()
  }) 
  pll_inst_ODSEL.gw_gnd := gw_gnd
  pll_inst_ODSEL.gw_gnd_0 := gw_gnd
  pll_inst_ODSEL.gw_gnd_1 := gw_gnd
  pll_inst_ODSEL.gw_gnd_2 := gw_gnd
  pll_inst_ODSEL.gw_gnd_3 := gw_gnd
  pll_inst_ODSEL.gw_gnd_4 := gw_gnd
  val pll_inst_PSDA = Wire(new Bundle { 
    val gw_gnd = Bool()
    val gw_gnd_0 = Bool()
    val gw_gnd_1 = Bool()
    val gw_gnd_2 = Bool()
  }) 
  pll_inst_PSDA.gw_gnd := gw_gnd
  pll_inst_PSDA.gw_gnd_0 := gw_gnd
  pll_inst_PSDA.gw_gnd_1 := gw_gnd
  pll_inst_PSDA.gw_gnd_2 := gw_gnd
  val pll_inst_DUTYDA = Wire(new Bundle { 
    val gw_gnd = Bool()
    val gw_gnd_0 = Bool()
    val gw_gnd_1 = Bool()
    val gw_gnd_2 = Bool()
  }) 
  pll_inst_DUTYDA.gw_gnd := gw_gnd
  pll_inst_DUTYDA.gw_gnd_0 := gw_gnd
  pll_inst_DUTYDA.gw_gnd_1 := gw_gnd
  pll_inst_DUTYDA.gw_gnd_2 := gw_gnd
  val pll_inst_FDLY = Wire(new Bundle { 
    val gw_gnd = Bool()
    val gw_gnd_0 = Bool()
    val gw_gnd_1 = Bool()
    val gw_gnd_2 = Bool()
  }) 
  pll_inst_FDLY.gw_gnd := gw_gnd
  pll_inst_FDLY.gw_gnd_0 := gw_gnd
  pll_inst_FDLY.gw_gnd_1 := gw_gnd
  pll_inst_FDLY.gw_gnd_2 := gw_gnd

  val pll_inst = Module(new PLL(pm))
  clkout := pll_inst.io.CLKOUT
  pll_inst.io.LOCK <> lock_o
  pll_inst.io.CLKOUTP <> clkoutp_o
  clkoutd := pll_inst.io.CLKOUTD
  pll_inst.io.CLKOUTD3 <> clkoutd3_o
  pll_inst.io.RESET := gw_gnd
  pll_inst.io.RESET_P := gw_gnd
  pll_inst.io.RESET_I := gw_gnd
  pll_inst.io.RESET_S := gw_gnd
  pll_inst.io.CLKIN := clkin
  pll_inst.io.CLKFB := gw_gnd
  pll_inst.io.FBDSEL := pll_inst_FBDSEL.asTypeOf(pll_inst.io.FBDSEL)
  pll_inst.io.IDSEL := pll_inst_IDSEL.asTypeOf(pll_inst.io.IDSEL)
  pll_inst.io.ODSEL := pll_inst_ODSEL.asTypeOf(pll_inst.io.ODSEL)
  pll_inst.io.PSDA := pll_inst_PSDA.asTypeOf(pll_inst.io.PSDA)
  pll_inst.io.DUTYDA := pll_inst_DUTYDA.asTypeOf(pll_inst.io.DUTYDA)
  pll_inst.io.FDLY := pll_inst_FDLY.asTypeOf(pll_inst.io.FDLY)

} //Gowin_PLL
